# Generated by Django 3.1.8 on 2023-11-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231101_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_no',
            field=models.PositiveIntegerField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
