# Generated by Django 3.1.8 on 2023-11-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_no',
        ),
    ]
