# Generated by Django 3.1.8 on 2023-11-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
